name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2']
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      REDIS_URL: redis://localhost:6379/0
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v1
      id: cache
      with:
        path: vendor/bundler
        key: ${{ hashFiles('Gemfile.lock') }}-${{ matrix.ruby }}
    - name: test
      run: |
        gem install bundler
        bundle install --path=vendor/bundler
        bundle exec rspec
        bundle exec rubocop
